### ISSUE TITLE
Building problems on OSX and Linux

### ISSUE THREAD

**Issue by ptulp** [tom-r/OpenCPN#1]
There are two issues found when building this under OSX and Linux.
1. The function rad2deg is defined twice. In dial.cpp where it is used and in tactics.cpp where it is defined but not used? Both OSX and Linux give errors here.
2. Both OSX and Linux crash when you select the manual heel setting in preferences and no NMEA data is entering the system. In OSX the crash is happening in tactics_pi.cpp line 4127.
   I think this is due that the variables mTWS and mTWA still have the NaN value which is not updated due to no NMEA data.

**Comment by tom-r** [comment]
Peter,
I implementeded your changes in the latest commit.
Please note that I separated the source now.

Thanks for helping,

Thomas
